---
- hosts: all
  become: true
  tasks:
  - name: Install Updates
    ansible.builtin.apt:
      update_cache: yes
  - name: Install latest version of nginx
    ansible.builtin.apt:
      name: nginx
      state: latest

  - name: Repair Broken Package Repo
    ansible.builtin.command: dpkg --configure -a
  
  - name: Copy web contents to web servers
    ansible.builtin.copy:
      src: ../files/index.html
      dest: /var/www/html/
      owner: cyber
      group: cyber
      mode: '0644'